repos:
- repo: https://github.com/psf/black
  rev: 23.12.1 # NOTE: If updating, also update the version in .github/workflows/lint.yaml
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/pycqa/isort
  rev: 5.13.2 # NOTE: If updating, also update the version in .github/workflows/lint.yaml
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 1.1.0
  hooks:
    - id: sync_with_poetry
      args: [
          '--all',  # Scan all dependencies in poetry.lock (main and dev)
      ]
